Функциональность Поиск.
Vintros/java-filmorate pull request #14
Opened 2022-11-07 16:00 UTC by AleksandrTimofeev1987

feature: добавить end-point GET /fimls/search
feature: добавить метод FilmService.searchFilmsByTitleOrDirector
feature: добавить метод DbFilmStorage.searchFilmsByTitle
feature: добавить метод DbFilmStorage.searchFilmsByDirector
feature: добавить метод DbFilmStorage.searchFilmsByTitleAndDirector

2022-11-07 16:29 UTC, BucketOnHead approved these changes
Я не увидел злостных нарушений, смог прицепиться только к пустой строке) Передаю Approve

2022-11-07 16:29 UTC, BucketOnHead commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectSearchParameterException.java
> +
Пустая строка)

2022-11-07 20:27 UTC, Vintros commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static void validateSearchParameter(String by) {
Валидацию лучше перенести в класс валидатор, а саму валидность проверять в сервисе(если это не проверка аннотациями ломбока).

2022-11-07 20:38 UTC, Vintros commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        List<Map.Entry<Long, String>> dataList = jdbcTemplate.query(sqlQuery, this::mapRowToMapEntryFilmIdDirectorName);
Мапу в лист не обязательно оборачивать. Достаточно в методе mapRowToMapEntryFilmIdDirectorName из параметров убрать (int i) и тогда сформируется сразу мапа

2022-11-07 20:52 UTC, AleksandrTimofeev1987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        List<Map.Entry<Long, String>> dataList = jdbcTemplate.query(sqlQuery, this::mapRowToMapEntryFilmIdDirectorName);
Так я не мапу извлекаю, а entry. Если убрать параметр (int i) то на выходе я получу один экземпляр entry, хотя записей у меня много. А оборачивать entry в лист или сразу обрабатывать особой разницы нет, все равно каждый entry проверять придется. Или я тебя не так понял?

2022-11-07 20:52 UTC, Vintros commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +                .map(this::getFilmById)
Запрос каждого фильма из БД отдельным методом это так называемая проблема n+1, когда увеличение количества объектов пропорционально увеличивает количество запросов к БД, этого нужно максимально избегать, количество запросов к БД не должно зависеть от количества запрашиваемых объектов.

2022-11-07 20:58 UTC, Vintros commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> searchFilmsByTitleOrDirector(@RequestParam String query,
Не рассмотрен вариант из ТЗ, где отсутствуют параметры запроса и нужно вернуть все фильмы.

2022-11-07 21:00 UTC, AleksandrTimofeev1987 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +                .map(this::getFilmById)
Поправлю

2022-11-07 21:23 UTC, Vintros commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                                @RequestParam(defaultValue = "title") String by) {
А зачем здесь defaultValue? Мне кажется если параметр by не передан вообще - нужно кидать эксепшен, а не додумывать за пользователя, что он хочет искать именно по названию, а например не по режиссеру.

2022-11-07 21:34 UTC, Vintros commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        List<Map.Entry<Long, String>> dataList = jdbcTemplate.query(sqlQuery, this::mapRowToMapEntryFilmIdDirectorName);
Да, в коде все правильно, это я немного затупил ). Замечание снимается

2022-11-07 21:37 UTC, Vintros requested changes
Несколько замечаний написал )

2022-11-08 11:53 UTC, AleksandrTimofeev1987 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                                @RequestParam(defaultValue = "title") String by) {
Поставил в самом начале. Забыл убрать, спасибо, что заметил.)

2022-11-08 12:53 UTC, BucketOnHead approved these changes

2022-11-08 12:53 UTC, BucketOnHead commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public List<Film> searchFilmsByTitleOrDirector(String query, String by) {
Предлагаю переименовать by на searchBy для большей ясности)

2022-11-08 13:58 UTC, Vintros commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Получен поисковый запрос: {}. Парамент поиска: {}", query, searchBy);
Очепятка: Парамент поиска

2022-11-08 14:03 UTC, Vintros commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +        String inSql = String.join(",", Collections.nCopies(matchingIds.size(), "?"));
+++

2022-11-08 14:15 UTC, Vintros approved these changes
Апрув!

2022-11-08 14:16 UTC, merged